---
- name: Run systemctl restart wgui.path
  listen: 'systemctl restart wgui.path'
  become: true
  ansible.builtin.systemd_service:
    name: 'wgui.path'
    enabled: true
    state: 'restarted'

- name: Run systemctl restart wgui.service
  listen: 'systemctl restart wgui.service'
  become: true
  ansible.builtin.systemd_service:
    name: 'wgui.service'
    enabled: true
    state: 'restarted'

- name: Run systemctl restart wireguard-ui.service
  listen: 'systemctl restart wireguard-ui.service'
  become: true
  ansible.builtin.systemd_service:
    name: 'wireguard-ui.service'
    enabled: true
    state: 'restarted'
