---
wireguardui__version: 'latest'

# config
wireguardui__conf_bind: '127.0.0.1:5000'
wireguardui__conf_int_address: '10.23.42.0/24'
wireguardui__conf_int_port: '51820'
wireguardui__conf_allowed_ips: "{{ wireguardui__conf_int_address }}"
wireguardui__conf_endpoint_ip: "{{ ansible_default_ipv4.address }}"

# network
wireguardui__wg_interface: 'wg0'
wireguardui__ipv4_forward: true
wireguardui__ipv6_forward: true

# Optional perform simple Versionscheck
submodules_versioncheck: false
