---
- name: Create /etc/wireguard-ui.conf config
  become: true
  ansible.builtin.template:
    src: 'templates/wireguard-ui.conf.j2'
    dest: '/etc/wireguard-ui.conf'
    owner: 'root'
    group: 'root'
    mode: '0640'
  notify: "systemctl restart wireguard-ui.service"

- name: Create wireguard-ui systemd service
  become: true
  ansible.builtin.template:
    src: 'templates/wireguard-ui.service.j2'
    dest: "/etc/systemd/system/wireguard-ui.service"
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: "systemctl restart wireguard-ui.service"

- name: Run systemctl start wireguard-ui.service
  become: true
  ansible.builtin.systemd_service:
    name: 'wireguard-ui.service'
    enabled: true
    state: 'started'
    daemon_reload: true
  notify: "systemctl restart wireguard-ui.service"
