---
- name: Run simple versionscheck (optional)
  ansible.builtin.include_tasks:
    file: 'versioncheck.yml'
  when: submodules_versioncheck | bool

- name: Set version for wireguard-ui
  ansible.builtin.include_tasks:
    file: 'set_version.yml'

- name: Download wireguard-ui
  ansible.builtin.include_tasks:
    file: 'download.yml'

- name: Create wireguard-ui config
  ansible.builtin.include_tasks:
    file: 'configure.yml'

- name: Create systemd unit
  ansible.builtin.include_tasks:
    file: 'systemd.yml'

- name: Enable IP Forward
  ansible.builtin.include_tasks:
    file: 'routing.yml'
